version: "3.7"

services:
  db_replic:
   image: "xivoxc/xivo-db-replication:${XIVOCC_TAG}.${XIVOCC_DIST}"

   environment:
   - JAVA_OPTS=-Xms64m -Xmx256m
   - ELASTICSEARCH
   - ELASTICTTL
   - ELASTICCLUSTER
   - DISABLEELASTIC=true
   - DB_HOST
   - REPORTING_DB_HOST
   - REPORTING_DATABASE_NAME
   - IS_MDS
   - IS_HA_SLAVE

   volumes:
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
   - /var/log/xivo-db-replication/:/opt/docker/var/log/xivo-db-replication/

   restart: always
